---
- name: Bootstrap VPN node
  import_playbook: bootstrap.yml

- name: Install 3x-ui
  hosts: xui_nodes
  become: true
  roles:
    - 3xui

- name: Register node in primary 3x-ui
  hosts: xui_nodes
  become: true
  roles:
    - 3xui-node

- name: Configure 3x-ui inbounds
  hosts: xui_nodes
  become: true
  roles:
    - 3xui-inbounds
