---
- name: Bootstrap node
  import_playbook: bootstrap.yml

- name: Deploy 3x-ui
  import_playbook: deploy.yml

- name: Register node in primary
  hosts: xui_nodes
  become: true

  roles:
    - 3xui-node
